const actionTypes = Object.freeze({
    //app
    APP_START_UP_COMPLETE: 'APP_START_UP_COMPLETE',
    SET_CONTENT_OF_CONFIRM_MODAL: 'SET_CONTENT_OF_CONFIRM_MODAL',
    CHANGE_LANGUAGE: 'CHANGE_LANGUAGE',

    //user
    ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',
    USER_LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
    USER_LOGIN_FAIL: 'USER_LOGIN_FAIL',
    PROCESS_LOGOUT: 'PROCESS_LOGOUT',

    // admin
    FETCH_GENDER_START: 'FETCH_GENDER_START',
    FETCH_GENDER_SUCCESS: 'FETCH_GENDER_SUCCESS',
    FETCH_GENDER_FAILED: 'FETCH_GENDER_FAILED',

    FETCH_POSITION_START: 'FETCH_POSITION_START',
    FETCH_POSITION_SUCCESS: 'FETCH_POSITION_SUCCESS',
    FETCH_POSITION_FAILED: 'FETCH_POSITION_FAILED',

    FETCH_ROLE_START: 'FETCH_ROLE_START',
    FETCH_ROLE_SUCCESS: 'FETCH_ROLE_SUCCESS',
    FETCH_ROLE_FAILED: 'FETCH_ROLE_FAILED',

    FETCH_ALL_USER_SUCCESS: 'FETCH_ALL_USER_SUCCESS',
    FETCH_ALL_USER_FAILED: 'FETCH_ALL_USER_FAILED',

    CREATE_USER_SUCCESS: 'CREATE_USER_SUCCESS',
    CREATE_USER_FAILED: 'CREATE_USER_FAILED',

    DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',
    DELETE_USER_FAILED: 'DELETE_USER_FAILED',

    UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',
    UPDATE_USER_FAILED: 'UPDATE_USER_FAILED',

    FETCH_TOP_DOCTOR_HOME_SUCCESS: 'FETCH_TOP_DOCTOR_HOME_SUCCESS',
    FETCH_TOP_DOCTOR_HOME_FAILED: 'FETCH_TOP_DOCTOR_HOME_FAILED',

    FETCH_ALL_DOCTOR_SUCCESS: 'FETCH_ALL_DOCTOR_SUCCESS',
    FETCH_ALL_DOCTOR_FAILED: 'FETCH_ALL_DOCTOR_FAILED',

    CREATE_DETAIL_INFO_DOCTOR_SUCCESS: 'CREATE_DETAIL_INFO_DOCTOR_SUCCESS',
    CREATE_DETAIL_INFO_DOCTOR_FAILED: 'CREATE_DETAIL_INFO_DOCTOR_FAILED',

    GET_DETAIL_INFO_DOCTOR_SUCCESS: 'GET_DETAIL_INFO_DOCTOR_SUCCESS',
    GET_DETAIL_INFO_DOCTOR_FAILED: 'GET_DETAIL_INFO_DOCTOR_FAILED',

    UPDATE_DETAIL_INFO_DOCTOR_SUCCESS: 'UPDATE_DETAIL_INFO_DOCTOR_SUCCESS',
    UPDATE_DETAIL_INFO_DOCTOR_FAILED: 'UPDATE_DETAIL_INFO_DOCTOR_FAILED',

    FETCH_ALL_CODE_SCHEDULE_TIME_SUCCESS:
        'FETCH_ALL_CODE_SCHEDULE_TIME_SUCCESS',
    FETCH_ALL_CODE_SCHEDULE_TIME_FAILED: 'FETCH_ALL_CODE_SCHEDULE_TIME_FAILED',

    SAVE_BULK_SCHEDULE_DOCTOR_SUCCESS: 'SAVE_BULK_SCHEDULE_DOCTOR_SUCCESS',
    SAVE_BULK_SCHEDULE_DOCTOR_FAILED: 'SAVE_BULK_SCHEDULE_DOCTOR_FAILED',

    GET_SCHEDULE_BY_DATE_SUCCESS: 'GET_SCHEDULE_BY_DATE_SUCCESS',
    GET_SCHEDULE_BY_DATE_FAILED: 'GET_SCHEDULE_BY_DATE_FAILED',

    // fetchPriceDoctor
    FETCH_PRICE_DOCTOR_SUCCESS: 'FETCH_PRICE_DOCTOR_SUCCESS',
    FETCH_PRICE_DOCTOR_FAILED: 'FETCH_PRICE_DOCTOR_FAILED',

    FETCH_PROVINCE_DOCTOR_SUCCESS: 'FETCH_PROVINCE_DOCTOR_SUCCESS',
    FETCH_PROVINCE_DOCTOR_FAILED: 'FETCH_PROVINCE_DOCTOR_FAILED',

    FETCH_PAYMENT_DOCTOR_SUCCESS: 'FETCH_PAYMENT_DOCTOR_SUCCESS',
    FETCH_PAYMENT_DOCTOR_FAILED: 'FETCH_PAYMENT_DOCTOR_FAILED',
});

export default actionTypes;
